### PR TITLE
fix: use factory in ConfigEvents dataclass field

### PR DESCRIPTION
**Pull request by fgsalomon**

### CODE REVIEW

**Comment by fgsalomon** [comment]
@acostapazo how can we test this?

**Comment by fgsalomon** [comment]
Where is this class used? 
There is another `ConfigEvents` in `event/shared/domain/config_events.py`. I'm starting to think that is obselete code 🤔

**Comment by acostapazo** [comment]
There are already some tests in: https://github.com/alice-biometrics/petisco/blob/bugfix/dataclass-error-in-python-3.11/tests/modules/event/unit/test_config_events.py

**Comment by fgsalomon** [comment]
> There are already some tests in: https://github.com/alice-biometrics/petisco/blob/bugfix/dataclass-error-in-python-3.11/tests/modules/event/unit/test_config_events.py

These tests test the other class I was talking about

**Pull request merged**
