### PR TITLE
feat(dependency): improve typing adding generic, add validation for d…

### PR DESCRIPTION
**Pull request by acostapazo**
…efined builders and prepare the code to v2 migration

### CODE REVIEW

**Comment by acostapazo** [comment]
## Proposal

We now define dependencies as:

```python
def get_repository_dependencies() -> list[Dependency]:
    repositories = [
        Dependency(
            name="document_repository",
            default_builder=Builder(SqlDocumentRepository, is_builder=True),
            envar_modifier="DOCUMENT_REPOSITORY_TYPE",
            builders={"inmemory": Builder(InMemoryDocumentRepository)},
        )]
   return repositories
```

Our proposal is to simplify the definition with something like: 

Type dependency and use new definition proposal:

```python
def get_repository_dependencies() -> list[Dependency]:
    repositories = [
        Dependency(
            DocumentRepository,
            alias="document_repository", # Optional to keep compatibility with `Container.get("document_repository")`
            builders={
               "default": Builder(SqlDocumentRepository, is_builder=True),
               "inmemory": Builder(InMemoryDocumentRepository)
            },
        )]
   return repositories
```
> **Note**
> The `envar_modifier` by default is the name of the type (`DocumentRepository`) + `_TYPE`. In this case `DOCUMENT_REPOSITORY_TYPE`.


Let's asume we have updated all the dependencies of my services keeping the alias (e.g "document_repository"). You can still accessing the container using: `Container.get("document_repository")`. If you keep this way of accessing to the Container instances you're not going to be benefiting of typing. So we recommend to use the base type to get the instance.

### Example:

Simplification of the dependencies:

```python
def get_repository_dependencies() -> list[Dependency]:
    repositories = [
        Dependency(
            DocumentRepository,
            builders={
               "default": Builder(SqlDocumentRepository, is_builder=True),
               "inmemory": Builder(InMemoryDocumentRepository)
            },
        )]
   return repositories
```

Typed access to `Container` instances:

```python
instance = Container.get(DocumentRepository)
```



> **Warning**
> This proposal is backward compatible. Some inputs are duplicated and should be deprecated in next releases -> v2 (breaking compatibility but reducing noise in parametrization)

**Review by franciscorode — APPROVED** [review]
I like it

**Comment by acostapazo** [comment]
A question has come up earlier when I was developing the proposal.

What should be the behavior of Container when two dependencies share type or alias?

Example:

```python
def get_repository_dependencies() -> list[Dependency]:
    repositories = [
        Dependency(
            DocumentRepository,
            builders={
               "default": Builder(SqlDocumentRepository, is_builder=True),
               "inmemory": Builder(InMemoryDocumentRepository)
            },
        ),
       Dependency(
            DocumentRepository,
            builders={
               "default": Builder(SqlDocumentRepository, is_builder=True),
               "inmemory": Builder(InMemoryDocumentRepository)
            },
        )
]
   return repositories
```

`Container.set_dependencies` have available an optional bool parameter (`overwrite`) to define this behavior:
* *overwrite is True*:  when type is repeated this will overwrite deleting (overwriting) previous defined dependency.
* *overwrite is False*: if some type or alias is duplicated this will raise an exception in Runtime requiring changes in dependencies definition.

Should the default `overwrite` value be true or false?

**Comment by franciscorode** [comment]
> Should the default `overwrite` value be true or false?

I would say false

**Pull request merged**
