### PR TITLE
feat(Uuid): research migration and limitations

### PR DESCRIPTION
**Pull request by acostapazo**
Researching new ways to represent `Uuid`.

We want `Uuid` to be represented as `UUID` in `pydantic.BaseModel` to avoid model duplication.

Screenshot 2023-09-12 at 13 14 15

 For example, now if you want to represent `UUID` in documentation but use internally `Uuid` you have to create two models:

```python
from pydantic import BaseModel
from uuid import UUID
from petisco import Uuid

class UserIn(BaseModel):
     id: UUID
     name: str
     age: int

class User(BaseModel):
    id: Uuid
    name: str
    age: int
```

In the following section I'm going to describe what have been tested:

## Use pydantic core schema

You can modify an object adding the following class method.

```
 @classmethod
        def __get_pydantic_core_schema__(
            cls, source: Any, handler: GetCoreSchemaHandler
        ) -> CoreSchema:
            return uuid_schema(version=4)
```

## Use `Annotated` 

I try the [pydantic way](https://github.com/pydantic/pydantic/blob/ed009ba0fa908b06fc2d3735b633885c4795096c/pydantic/types.py#L635)

```python
UUID4 = Annotated[UUID, UuidVersion(4)]
```

where `UuidVersion` is an annotation class:

```python
@_dataclasses.dataclass(**_internal_dataclass.slots_true)
class UuidVersion:
    uuid_version: Literal[1, 3, 4, 5]

    def __get_pydantic_json_schema__(
        self, core_schema: core_schema.CoreSchema, handler: _annotated_handlers.GetJsonSchemaHandler
    ) -> JsonSchemaValue:
        field_schema = handler(core_schema)
        field_schema.pop('anyOf', None)  # remove the bytes/str union
        field_schema.update(type='string', format=f'uuid{self.uuid_version}')
        return field_schema

    def __get_pydantic_core_schema__(
        self, source: Any, handler: _annotated_handlers.GetCoreSchemaHandler
    ) -> core_schema.CoreSchema:
        return core_schema.uuid_schema(version=self.uuid_version)

    def __hash__(self) -> int:
        return hash(type(self.uuid_version))
```

## Inherit from `UUID` and keep legacy functions to be compatible 

https://github.com/alice-biometrics/petisco/pull/412/files

I thought this might be the solution, but it seems that UUID is not case sensitive, and this is a huge problem. ⚠️ ⚠️ 
Errors: https://github.com/alice-biometrics/petisco/actions/runs/6158562966

To reproduce errors you can run:

```console
export USE_NEW_UUID=True
pytest -k TestUuid
```

Also you can run a fastapi app to test schema:

```console
export USE_NEW_UUID=True
uvicorn examples.fastapi.main:app --reload
```

### CODE REVIEW

**Comment by fgsalomon** [comment]
I'm a bit lost...

Does the option "Use pydantic core schema" work? If it works I vote to use it, it seems the simplest one.

Regarding the case sensitivity the [RFC says](https://datatracker.ietf.org/doc/html/rfc4122#section-3):

>The hexadecimal values "a" through "f" are output as
      lower case characters and are case insensitive on input.

So, in option 3 it should not be problem that UUID is not case sensitive.

**Comment by acostapazo** [comment]
Added some progress in [d7d700b](https://github.com/alice-biometrics/petisco/pull/412/commits/d7d700bb773aa9308bc357b0caf4b4b154c3825e)

The problem now is how to obtain `Uuid` value from `FastAPI` input.

To check it out, just type: `uvicorn examples.fastapi.main:app --reload` and you will obtain new uuid available:

Screenshot 2023-09-25 at 16 28 10
Screenshot 2023-09-25 at 16 28 05

This is fantastic, but not enough, I guess. In the code (https://github.com/alice-biometrics/petisco/blob/feature/improved-uuid/examples/fastapi/main.py#L16) we obtain `uuid.UUID` values instead `petisco.Uuid`. It's a pity as we cannot use `.value` available in the last one, and back compatibility is affected. :(

I have tried inheriting and not inheriting from the UUID 🤔.

**Comment by acostapazo** [comment]
We've tried to resolve the above issues in [0185445](https://github.com/alice-biometrics/petisco/pull/412/commits/0185445dcde93561cecf9d95230da2943a27cacd)

The new `Uuid` implementation inherits from str and defines a valid schema for OpenAPI.

Unfortunately, this is not valid to be used in `BaseModels` as they expect a UUID (from schema) and not a `Uuid`

```
E   pydantic_core._pydantic_core.ValidationError: 1 validation error for UserCreated
E   user_id
E     UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=f8a4d2ee-4be4-4e01-8738-d75d7131ac12, input_type=Uuid]
E       For further information visit https://errors.pydantic.dev/2.1/v/uuid_type
```

For 

```python
class UserCreated(DomainEvent):
    user_id: Uuid

user_created = UserCreated(user_id=Uuid.v4())
```

**Comment by fgsalomon** [comment]
> We've tried to resolve the above issues in [0185445](https://github.com/alice-biometrics/petisco/pull/412/commits/0185445dcde93561cecf9d95230da2943a27cacd)
> 
> The new `Uuid` implementation inherits from str and defines a valid schema for OpenAPI.
> 
> Unfortunately, this is not valid to be used in `BaseModels` as they expect a UUID (from schema) and not a `Uuid`
> 
> ```
> E   pydantic_core._pydantic_core.ValidationError: 1 validation error for UserCreated
> E   user_id
> E     UUID input should be a string, bytes or UUID object [type=uuid_type, input_value=f8a4d2ee-4be4-4e01-8738-d75d7131ac12, input_type=Uuid]
> E       For further information visit https://errors.pydantic.dev/2.1/v/uuid_type
> ```
> 
> For
> 
> ```python
> class UserCreated(DomainEvent):
>     user_id: Uuid
> 
> user_created = UserCreated(user_id=Uuid.v4())
> ```

I've opened a discussion [here](https://github.com/pydantic/pydantic/discussions/7668).

**Pull request merged**
